### ISSUE TITLE
Running "sass:build" (sass) task Error: File to import not found or unreadable Aborted due to warnings.

### ISSUE THREAD

**Issue by stefek99** [blockchain/My-Wallet-V3-Frontend#1375]
```
ERROR in ./~/css-loader!./~/sass-loader!./helperApp/plaid/plaid.scss
Module build failed:
@import "../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables";
^
      File to import not found or unreadable: ../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables.
Parent style sheet: stdin
      in /Users/zen/Dropbox/Musafa/dev/My-Wallet-V3-Frontend/helperApp/plaid/plaid.scss (line 2, column 1)
 @ ./helperApp/plaid/plaid.scss 4:14-118

ERROR in ./helperApp/plaid/plaid.scss
Module build failed: ModuleBuildError: Module build failed:
@import "../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables";
```

```
Running "sass:build" (sass) task
>> Error: File to import not found or unreadable: ../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables
>>        Parent style sheet: /Users/zen/Dropbox/Musafa/dev/My-Wallet-V3-Frontend/assets/css/_bootstrap-blockchain.scss
>>         on line 2 of assets/css/_bootstrap-blockchain.scss
>> >> @import "../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/va
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.
```

**Comment by plondon** [comment]
Hi @stefek99 thanks for using the wallet! It looks like it's trying to import a bower_component but can't. Have you run `bower install` in the project yet?

**Comment by stefek99** [comment]
Did ```bower install```

Now ```make server```


```
grunt dist --versionFrontend=v1.11.11; --rootDomain=blockchain.info --apiDomain=api.blockchain.info --network=
Running "dist" task
Helper App URL missing
/bin/sh: --rootDomain=blockchain.info: command not found
make: *** [dist_fixed_domain] Error 127
```

**Comment by plondon** [comment]
Thanks, can you try just `make dist` now?

**Comment by stefek99** [comment]
```make dist```

```DIST=1 ./node_modules/.bin/webpack
[BABEL] Note: The code generator has deoptimised the styling of "/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
Hash: e48ecf3d156f2badacde
Version: webpack 1.14.0
Time: 11521ms
                                            Asset       Size  Chunks             Chunk Names
              plaid/plaid-e48ecf3d156f2badacde.js    4.03 kB       0  [emitted]  plaid/plaid
sift-science/sift-science-e48ecf3d156f2badacde.js    4.05 kB       1  [emitted]  sift-science/sift-science
             plaid/plaid-e48ecf3d156f2badacde.css    18.8 kB       0  [emitted]  plaid/plaid
                                 plaid/index.html  708 bytes          [emitted]
                          sift-science/index.html  649 bytes          [emitted]
    + 12 hidden modules
Child html-webpack-plugin for "plaid/index.html":
        + 4 hidden modules
Child html-webpack-plugin for "sift-science/index.html":
        + 4 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
grunt dist --versionFrontend=v1.11.11; --rootDomain= --apiDomain=api.blockchain.info --network= --webSocketURL= --helperAppUrl=
Running "dist" task
Helper App URL missing
/bin/sh: --rootDomain=: command not found
make: *** [dist] Error 127
```

---

```make server```

```grunt dist --versionFrontend=v1.11.11; --rootDomain=blockchain.info --apiDomain=api.blockchain.info --network=
Running "dist" task
Helper App URL missing
/bin/sh: --rootDomain=blockchain.info: command not found
make: *** [dist_fixed_domain] Error 127```

---

![image](https://user-images.githubusercontent.com/249703/32973487-aa571616-cbef-11e7-8f76-690311d14a41.png)

Please advise what to configure to use localhost...

What to put

**Comment by plondon** [comment]
@stefek99 seems the command `/bin/sh` cannot be found. What is the output of `which sh`?

**Comment by stefek99** [comment]
```hich sh
/bin/sh```

**Comment by plondon** [comment]
Thanks
Can you attach the full output of:
```
make clean
make dist```

**Comment by stefek99** [comment]
```
sudo make clean
Password:
rm -rf build dist node_modules bower_components npm-shrinkwrap.json coverage .sass-cache helperApp/build helperApp/dist
npm cache clean
```

```
  └─┬ webpack-core@0.6.9
    └── source-map@0.4.4

npm WARN angular-blockchain-wallet@1.11.4 No license field.
./check_bad_strings.rb
grunt build
Running "html2js:main" (html2js) task
Successfully converted 134 html templates to js.

Running "babel:build" (babel) task

Running "shell:webpack" (shell) task
[BABEL] Note: The code generator has deoptimised the styling of "/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
Hash: 28099a7988822e049c2f
Version: webpack 1.14.0
Time: 16639ms
                       Asset       Size  Chunks             Chunk Names
              plaid/plaid.js    12.3 kB       0  [emitted]  plaid/plaid
sift-science/sift-science.js    4.04 kB       1  [emitted]  sift-science/sift-science
            plaid/index.html  617 bytes          [emitted]
     sift-science/index.html  628 bytes          [emitted]
    + 11 hidden modules

ERROR in ./~/css-loader!./~/sass-loader!./helperApp/plaid/plaid.scss
Module build failed:
@import "../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables";
^
      File to import not found or unreadable: ../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables.
Parent style sheet: stdin
      in /Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/helperApp/plaid/plaid.scss (line 2, column 1)
 @ ./helperApp/plaid/plaid.scss 4:14-118

ERROR in ./helperApp/plaid/plaid.scss
Module build failed: ModuleBuildError: Module build failed:
@import "../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables";
^
      File to import not found or unreadable: ../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables.
Parent style sheet: stdin
      in /Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/helperApp/plaid/plaid.scss (line 2, column 1)
    at DependenciesBlock.onModuleBuildFailed (/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
    at nextLoader (/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
    at /Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at context.callback (/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
    at Object.onRender (/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/sass-loader/index.js:273:13)
    at Object.<anonymous> (/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/sass-loader/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/sass-loader/node_modules/async/dist/async.js:958:16)
    at options.error (/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/node-sass/lib/index.js:289:32)
Child html-webpack-plugin for "plaid/index.html":
        + 4 hidden modules
Child html-webpack-plugin for "sift-science/index.html":
        + 4 hidden modules
Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader!./~/sass-loader!./helperApp/plaid/plaid.scss
    Module build failed:
    @import "../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables";
    ^
          File to import not found or unreadable: ../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables.
    Parent style sheet: stdin
          in /Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/helperApp/plaid/plaid.scss (line 2, column 1)

Running "concat:wallet" (concat) task

Running "concat:qrReader" (concat) task

Running "concat:bcPhoneNumber" (concat) task

Running "sass:build" (sass) task
>> Error: File to import not found or unreadable: ../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/variables
>>        Parent style sheet: /Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/assets/css/_bootstrap-blockchain.scss
>>         on line 2 of assets/css/_bootstrap-blockchain.scss
>> >> @import "../../bower_components/bootstrap-sass/assets/stylesheets/bootstrap/va
>>    ^
Warning:  Use --force to continue.

Aborted due to warnings.
make: *** [build] Error 6
```


# Tried `bower install` now and `sudo make dist` again:

```
udo make dist
Password:
DIST=1 ./node_modules/.bin/webpack
[BABEL] Note: The code generator has deoptimised the styling of "/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "/Users/zen/Dropbox/Musafa/dev/blockchain.info-My-Wallet-V3-Frontend/node_modules/lodash/lodash.js" as it exceeds the max of "500KB".
Hash: e48ecf3d156f2badacde
Version: webpack 1.14.0
Time: 14258ms
                                            Asset       Size  Chunks             Chunk Names
              plaid/plaid-e48ecf3d156f2badacde.js    4.03 kB       0  [emitted]  plaid/plaid
sift-science/sift-science-e48ecf3d156f2badacde.js    4.05 kB       1  [emitted]  sift-science/sift-science
             plaid/plaid-e48ecf3d156f2badacde.css    18.8 kB       0  [emitted]  plaid/plaid
                                 plaid/index.html  708 bytes          [emitted]
                          sift-science/index.html  649 bytes          [emitted]
    + 12 hidden modules
Child html-webpack-plugin for "plaid/index.html":
        + 4 hidden modules
Child html-webpack-plugin for "sift-science/index.html":
        + 4 hidden modules
Child extract-text-webpack-plugin:
        + 2 hidden modules
grunt dist --versionFrontend=v1.11.11; --rootDomain= --apiDomain=localhost --network= --webSocketURL= --helperAppUrl=
Running "dist" task
Helper App URL missing
/bin/sh: --rootDomain=: command not found
make: *** [dist] Error 127
```

**Comment by stefek99** [comment]
@plondon ping nudge...

*(I'm a developer myself, working on docs for the company, not much spare capacity to debug build issues)*

```/bin/sh: --rootDomain=: command not found```

Tell me where to set it up...

**Comment by plondon** [comment]
Hey @stefek99, sorry you're still having issues.

I also ran across an error today when running `make dist`, and it was because my npm version was updated recently. I downgraded back to npm@4 and make dist worked. Can you try the same?

`npm install -g npm@4`

**Comment by stefek99** [comment]
Not really, worried about breaking changes elsewhere.

Node version manager: https://github.com/creationix/nvm

23k+ stars on GitHub.

**Comment by plondon** [comment]
Gotcha, can you please let me know which npm version you are on so I can replicate your issue exactly? Thanks

**Comment by stefek99** [comment]
```
npm --version
3.10.10

node --version
v6.9.5
```

**Comment by plondon** [comment]
Hmm, unable to replicate with those versions.

Are you on the latest master branch of My-Wallet-V3-Frontend? I ask because this task: `Running "shell:webpack" (shell) task` is skipped over here: https://github.com/blockchain/My-Wallet-V3-Frontend/blob/master/Makefile#L43

**Comment by stefek99** [comment]
I'll try on a fresh VM and see how it goes.

**Comment by plondon** [comment]
Thank you!

**Comment by plondon** [comment]
Please let me know how that goes :)

**Comment by stefek99** [comment]
Realistically speaking - no timeline - that's a perfect job for an apprentice type of role...

Allow someone junior to play with the VM, installation, etc...

Too busy in this lifetime.

Feel free to close as appropriate. 

Did you notice this error / warning message? `/bin/sh: --rootDomain=: command not found`

Maybe it expects some value to be set?
